<?php

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes - Generated by Vemto
|--------------------------------------------------------------------------
|
| It is not recommended to edit this file directly. Although you can do so,
| it will generate a conflict on Vemto's next build.
|
*/

// Dashboard
Route::prefix('/dashboard')
    ->name('dashboard.')
    ->group(function (): void {
    });

// Site
Route::prefix('/')->group(function (): void {
});

// Filament Panel
Route::prefix('/panel')
    ->name('panel.')
    ->group(function (): void {
    });
